config/routes.rb
Rails.application.routes.draw do
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-tag"></i> Denominación </span>
      
      <%= form.text_field :name, id: :product_name, :class=>"form-control", :type=>"text", :placeholder=>"Denominación" %>
  </div>
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-shopping-cart"></i> Precio </span>
    <%= form.text_field :price, id: :product_name, :class=>"form-control", :type=>"text", :placeholder=>"Precio" %>
  </div>
  <div class="panel">
  </div>
  <div class="container-fluid">
    <div class="row">
        <div class="col-sm-11">
        </div>
        <div class="col-sm-1">
          <div class="btn-group">
            <div class="actions" >
              <%= form.submit :Aceptar, class: 'btn btn-success'%>
            </div>  
          </div>
        </div>
    </div>
  </div>
<% end %>

app/views/products/_product_footer.html.erb
<footer class="container-fluid text-center">
    <p>Te enviamos el inventario de productos a tu email</p>  
    <form class="form-inline">Correo electrónico:
      <input type="email" class="form-control" size="50" placeholder="Email Address">
      <button type="button" class="btn btn-danger">Solicitar</button>
    </form>
</footer>

app/views/products/_product_header.html.erb
<%= javascript_include_tag( 'application' ) %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
/* Remove the navbar's default rounded borders and increase the bottom margin */ 
.navbar {
  margin-bottom: 50px;
  border-radius: 0;
}

/* Remove the jumbotron's default bottom margin */ 
 .jumbotron {
  margin-bottom: 0;
}

/* Add a gray background color and some padding to the footer */
footer {
  background-color: #f2f2f2;
  padding: 25px;
}
</style>



<div class="jumbotron">
    <div class="container text-center">
        <h1>Mi tienda</h1>
        <p>Inventario de <strong>productos</strong></p>
    </div>
</div>
<nav class="navbar navbar-inverse">
  <div class="container-fluid"  
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand" href="/products" data-toggle="tooltip" title="Inicio"> Shop </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <li class="active"> <a href="#">Home</a></li>
            <li><a href="#">Page 1</a></li>
            <li><a href="#">Page 2</a></li>
            <li><a href="#">Page 3</a></li>
        </ul>
        <button class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#myModal">Ayuda</button>
 
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
    <div class="modal fade" id="myModal"  role="dialog">
    <div class="modal-dialog"> 
        
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ayuda en pantalla modal</h4>
            </div>
            <div class="modal-body">
                <p>Ayuda al usuario para indicarle las opciones de la aplicación.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
 </div>
</div>
</nav>

app/views/products/edit.html.erb
<%= render 'product_header' %>
<div class="container">
<%= render 'form', product: @product %>


<div class="btn-group">
    <%= link_to 'Mostrar', @product, :class => "btn btn-info", :type =>"button"%> 
    <%= link_to 'Atrás', products_path , :class => "btn btn-info", :type =>"button" %>
</div>
<%= render 'product_footer' %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'product_header' %>
<div class="container">
<!-- <div class="row"> -->
<!-- <div class="col-sm-8"> -->
  <div class="table-responsive" >
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Denominación</th>
        <th>Precio</th>
        <th colspan="3"><p class="text-center">Acciones<p></th>
      </tr>
    </thead>
<!-- </div> -->
<!-- <div class="col-sm-4"> -->
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td>
          <div class="btn-group">
          <td><%= link_to 'Mostrar', product , :type =>"button", :class => "btn btn-primary" %></td>
          <td><%= link_to 'Editar', edit_product_path(product), :type =>"button", :class => "btn btn-warning" %></td>
          <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Are you sure?' } , :type =>"button", :class => "btn btn-danger" %></td>
        </div>
          </td>
          
        </tr>
      <% end %>
    </tbody>
    <!-- </div> -->
  </table>
  <!-- </div> -->
<br>
<div class="row">
  <div class="col-sm-10">
    <a href="/products/new" class="btn btn-info" role="button">Alta de Producto</a>
  </div>
 
</div>
<br> </br>
<%= render 'product_footer' %>
</div>
</div>
</div>

app/views/products/new.html.erb
<%= render 'product_header' %>
<div class="container">

<%= render 'form', product: @product %>
<div class="btn-group">

<%= link_to 'Atrás', products_path , :class => "btn btn-info", :type =>"button" %>
</div>
<%= render 'product_footer' %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'product_header' %>
<div class="container">
<div class="panel panel-primary">
  <div class="panel-body"><%= @product.name %></div>
  <div class="panel-footer"><%= @product.price %></div>
</div>




<div class="btn-group">
  <%= link_to 'Editar', edit_product_path(@product), :class => "btn btn-info", :type =>"button" %> 
  <%= link_to 'Atrás', products_path , :class => "btn btn-info", :type =>"button" %>
</div>
</div>
<%= render 'product_footer' %>